# ----------------------------------------------------------------------------------------------------------------------
# This is the in-app documentation configuration file for the English language.
# It defines all the text displayed in the app in the corresponding variables.
# To create a configuration file for another language, simply copy this file and set all its variables in the desired language.
# You can then run the app with the `--language` parameter and give it the name of the configuration file you want to use.
#
# Example:
#       `python app.py --language=fr`
# If the specified file is not found, the app reverts to this file.
# ----------------------------------------------------------------------------------------------------------------------

description = """
Welcome to Escribito—your companion for crafting and exploring AI-generated dialogues!

- Use the left panel to insert new messages or let the model generate responses. Click “Send” (or press Enter) to continue.
- When the “Message” field is empty, Escribito uses the LLM to produce the next reply. Otherwise, it appends your typed text to the conversation, depending on which character you’ve selected.
- The right panel lets you fine-tune the LLM’s parameters and customize the characters’ names and backstories. Refer to each panel's guidance for more details.

Have fun creating dynamic, character-driven exchanges!
"""

# user control panel
[user_panel]
role_selector_label = "Character"
message_label = "Message"
send_btn_label = "Send"
download_btn_label = "Download"

# character definition panel
[character_panel]
title = "Character Definition"
description = """
Define each character’s name and story. Include motivations, objectives, and relevant context to keep conversations engaging and coherent. Provide enough background on why your characters are interacting.
"""
character_a_name_label = "Name"
character_a_story_label = "Story"
character_b_name_label = "Name"
character_b_story_label = "Story"
character_a_name = "John"
character_a_story = "A middle-aged father of two, happily enjoying life. He’s an old friend of Stella and has dropped by for a coffee."
character_b_name = "Stella"
character_b_story = "A middle-aged woman, single, who invited her friend John for coffee to seek his advice on a pressing concern."

[llm_panel]
title = "LLM Control"
description = """
Adjust the parameters that guide your AI’s responses. Experiment with different settings or rely on the recommended defaults.
"""
temperature_btn_label = "Temperature"
temperature_btn_info = "Controls how creative or bold the AI’s responses are. Higher values produce more unexpected replies."
model_btn_label = "Model"
model_btn_info = "Select which AI model to use. Larger models may yield better results but can be slower or more expensive."